version: "3"

services:
  influxdb:
    image: influxdb:latest
    ports:
      - "1111:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/config/:/etc/influxdb/

  chronograf:
    image: chronograf:latest
    ports:
      - "2222:8008"
    links:
      - influxdb
      - kapacitor
    environment:
      - PORT=8008
    volumes:
      - ./chronograf/data/:/var/lib/chronograf/

  jupyter:
    build: ./jupyter
    ports:
      - "7777:8888"
    environment:
      - PASSWORD=password
    volumes:
      - ./jupyter/notebooks:/notebooks

  flask_web:
    build: ./flask_web
    ports:
      - "6500:6500"
    links:
      - influxdb
    volumes:
      - ./flask_web/:/usr/src/app/

  kapacitor:
    image: kapacitor:latest
    ports:
      - "3333:9092"
    links:
      - influxdb
<<<<<<< HEAD
      #- flask_line
=======
  #    - flask_line
>>>>>>> feature/3-Alert
    volumes:
      - ./kapacitor/data/:/var/lib/kapacitor
      - ./kapacitor/config/:/etc/kapacitor/
      - ./kapacitor/tasks:/etc/kapacitor/load/tasks:ro

<<<<<<< HEAD
  #flask_line:
    #build: ./flask_line
    #ports:
            #  - "4649:5000"
    # links:
    #    - influxdb
    #volumes:
            #  - ./flask_line/:/usr/src/app/
=======
  # flask_line:
  #   build: ./flask_line
  #   ports:
  #     - "4649:5000"
  #   volumes:
  #     - ./flask_line/:/usr/src/app/
>>>>>>> feature/3-Alert
