version: "3"

services:
  influxdb:
    image: influxdb:latest
    ports:
      - "1111:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/config/:/etc/influxdb/

  chronograf:
    image: chronograf:latest
    ports:
      - "2222:8008"
    links:
      - influxdb
      - kapacitor
    environment:
      - PORT=8008
    volumes:
      - ./chronograf/data/:/var/lib/chronograf/

  jupyter:
    build: ./jupyter
    ports:
      - "7777:8888"
    environment:
      - PASSWORD=password
    volumes:
      - ./jupyter/notebooks:/notebooks

  flask_web:
    build: ./flask_web
    ports:
      - "6500:6500"
    links:
      - influxdb
    volumes:
      - ./flask_web/:/usr/src/app/
